### ISSUE TITLE
Would love to use this in Ableton 10 OS X.

### ISSUE THREAD

**Issue by carlaviktor** [xnamahx/RulosMutantes#1]
Hi, I tried it in Ableton 10 on OS X and it doesn't seem to produce any sound. I clearly states in the README that this is for Windows. Is there a lot of work to get it working on OS X as well?

**Comment by xnamahx** [comment]
Hi @vikfroberg 
It shouldnt be that hard to compile the source for OSX, but I dont have access to such devices to try it.

**Comment by carlaviktor** [comment]
Thanks! I'll give it a shot and make a PR! Haven't worked with Max before, any pointers as welcome 😊
